name: Secret Scanning (TruffleHog)

on:
  push:
    branches:
      - main  # o tu rama principal
  pull_request:

jobs:
  trufflehog-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Ejecutar TruffleHog
        uses: trufflesecurity/trufflehog@main
        with:
          path: .
          output: trufflehog-results.json
